
import React from 'react';
import WeeklyProgress from './dashboard/WeeklyProgress';
import Strengths from './dashboard/Strengths';
import ProblemAreas from './dashboard/ProblemAreas';
import AIRecommendations from './dashboard/AIRecommendations';
import { useGlobalData } from '@/contexts/GlobalDataProvider';
import { EmptyStateView } from './ui/empty-state-view';

export const LifeQualityTracker: React.FC = () => {
  const { appState } = useGlobalData();

  const handleGetStarted = () => {
    // Navigate to ratings page or show onboarding
    window.location.href = '/ratings';
  };

  const handleViewDemo = () => {
    // Demo data is already generated by EmptyStateView
    window.location.reload();
  };

  if (appState.userState === 'empty') {
    return (
      <EmptyStateView 
        onGetStarted={handleGetStarted}
        onViewDemo={handleViewDemo}
      />
    );
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <WeeklyProgress />
        <Strengths />
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ProblemAreas />
        <AIRecommendations />
      </div>
    </div>
  );
};

export default LifeQualityTracker;
